export const stringConstants = {
    logo: "Destin<span class='text-blue-600'>AI</span>",
    generateTrip: "Generate Trip",
    title: "<span class='text-blue-600' >Discover. Plan. Explore.</span> Your Ultimate Travel Companion Awaits",
    subtitle:
        "Unlock the world with AI-powered trip planning. From crafting tailored itineraries to uncovering hidden gems, we make your dream adventures effortless and unforgettable.",
    signin: "Sign in",
    getStarted: "Get Started",
    createTripTitle: "Tell us your travel preferences🌴",
    createTripSubtitle:
        "Just provide some basic information, and our trip planner will generate a customized itinerary based on your preferences.",
    destinationLabel: "What is your destination of choice?",
    destinationPlaceholder: "Enter your destination",
    daysLabel: "How many days are you planning your trip (1-10 days)?",
    daysPlaceholder: "Ex.2",
    budgetHeading: "What is your budget?",
    travelCompanionHeading: "Who will be your travel companion?",
    signInWithGoogle: "Sign in with Google",
    authDialogDesc: "To continue, please sign in with your Google account.",
    days: (val: string) => (val === "1" ? "Day" : "Days"),
    hotelRecommendation: "Hotel Recommendation",
    placesToVisit: "Places to Visit",
    myTrips: "My Trips",
    logout: "Log out",
    pleaseLogin: "Please login to view your trip.",
    somethingWentWrong: "Something went wrong!",
    viewManageTrips:
        "View and manage all your saved trips in one convenient place.",
    tripDays: (val: string) => `${val} ${val === "1" ? "day" : "days"}`,
    budget: (val: string) => val !== "Budget-Friendly" && "Budget",
    footerText: "Built with passion by Arun Kumar.",
    createTrip: "Create Trip",
    areYouSure: "Are you absolutely sure?",
    deleteConfirmation:
        " This action cannot be undone. This will permanently delete your trip and remove your data from our servers.",
    cancel: "Cancel",
    delete: "Delete",
    noTripsAvailable: "No Trip Available!",
    plsSelectDestination: "Please select your destination!",
    allFieldsRequired: "All fields are required!",
    pleaseEnterNoOfDays: "Please enter a number of days between 1 and 10",
    travelPlanCreatedSuccesfully: "Travel plan created successfully!",
    tripNotFound: "Trip not found!",
};
